from django.urls import path

from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('category/<int:category_id>/',
         sort_products_by_category_view,
         name="sort_by_category"),
    path('product/<int:product_id>/',
         product_detail_view,
         name="product_detail"),
    path('search/',
         search_view,
         name="search"),
    path('login/',
         user_login_view,
         name="login"),
    path('registration/',
         user_registration_view,
         name="registration"),
    path('logout/',
         user_logout_view,
         name="logout"),
    path('profile/<int:user_id>',
         check_profile_view,
         name="profile"),
    path('change_profile/<int:user_id>/',
         change_profile_data,
         name="change_profile"),
    path('cart/',
         cart_view,
         name='cart'),
    path('cart/add/<int:product_id>/',
         add_to_cart_view,
         name='add_to_cart'),
    path('cart/remove/<int:cart_item_id>/',
         remove_from_cart_view,
         name='remove_from_cart'),
    path('cart/update/<int:cart_item_id>/',
         update_cart_item_view,
         name='update_cart_item'),
    path('add_to_favorites/<int:product_id>/',
         add_to_favorites_view,
         name='add_to_favorites'),
    path('favorites/',
         favorites_view,
         name='favorites'),
    path('favorites/remove/<int:favorite_item_id>/',
         remove_from_favorites_view,
         name='remove_from_favorites'),
    path('product/<int:product_id>/add_review/',
         add_review_view,
         name='add_review'),
    path('order/create/',
         order_create_view,
         name='order_create'),
    path('order/confirmation/<int:order_id>/',
         order_confirmation_view,
         name='order_confirmation')
]
